def __v_to():
    return [
        ('afford', 'affords', 'afforded'),
        ('agree', 'agrees', 'agreed'),
        ('aim', 'aims', 'aimed'),
        ('appear', 'appears', 'appeared'),
        ('arrange', 'arranges', 'arranged'),
        ('ask', 'asks', 'asked'),
        ('attempt', 'attempts', 'attempted'),
        ('choose', 'chooses', 'chose'),
        ('claim', 'claims', 'claimed'),
        ('dare', 'dares', 'dared'),
        ('decide', 'decides', 'decided'),
        ('demand', 'demands', 'demanded'),
        ('deserve', 'deserves', 'deserved'),
        ('expect', 'expects', 'expected'),
        ('fail', 'fails', 'failed'),
        ('fight', 'fights', 'fought'),
        ('forget', 'forgets', 'forgot'),
        ('grow', 'grows', 'grew'),
        ('help', 'helps', 'helped'),
        ('hesitate', 'hesitates', 'hesitated'),
        ('hope', 'hopes', 'hoped'),
        ('intend', 'intends', 'intended'),
        ('learn', 'learns', 'learned'),
        ('manage', 'manages', 'managed'),
        ('mean', 'means', 'meant'),
        ('need', 'needs', 'needed'),
        ('offer', 'offers', 'offered'),
        ('plan', 'plans', 'planned'),
        ('prepare', 'prepares', 'prepared'),
        ('pretend', 'pretends', 'pretended'),
        ('promise', 'promises', 'promised'),
        ('refuse', 'refuses', 'refused'),
        ('seem', 'seems', 'seemed'),
        ('tend', 'tends', 'tended'),
        ('threaten', 'threatens', 'threatened'),
        ('wait', 'waits', 'waited'),
        ('want', 'wants', 'wanted'),
        ('wish', 'wishes', 'wished')
    ]


def __v_ing():
    return [
        ('admit', 'admits', 'admitted'),
        ('appreciate', 'appreciates', 'appreciated'),
        ('avoid', 'avoids', 'avoided'),
        ('consider', 'considers', 'considered'),
        ('delay', 'delays', 'delayed'),
        ('deny', 'denies', 'denied'),
        ('describe', 'describes', 'described'),
        ('dislike', 'dislikes', 'disliked'),
        ('enjoy', 'enjoys', 'enjoyed'),
        ('fancy', 'fancies', 'fancied'),
        ('finish', 'finishes', 'finished'),
        ('hate', 'hates', 'hated'),
        ('imagine', 'imagines', 'imagined'),
        ('keep', 'keeps', 'kept'),
        ('like', 'likes', 'liked'),
        ('look forward to', 'looks forward to', 'looked forward to'),
        ('love', 'loves', 'loved'),
        ('mention', 'mentions', 'mentioned'),
        ('mind', 'minds', 'minded'),
        ('miss', 'misses', 'missed'),
        ('risk', 'risks', 'risked'),
        ('stand', 'stands', 'stood'),
        ('stop', 'stops', 'stopped'),
        ('suggest', 'suggests', 'suggested')
    ]


def __v_obj_to():
    return [
        ('advise', 'advises', 'advised'),
        ('allow', 'allows', 'allowed'),
        ('ask', 'asks', 'asked'),
        ('beg', 'begs', 'begged'),
        ('cause', 'causes', 'caused'),
        ('choose', 'chooses', 'chose'),
        ('enable', 'enables', 'enabled'),
        ('encourage', 'encourages', 'encouraged'),
        ('expect', 'expects', 'expected'),
        ('forbid', 'forbids', 'forbade'),
        ('force', 'forces', 'forced'),
        ('get', 'gets', 'got'),
        ('help', 'helps', 'helped'),
        ('invite', 'invites', 'invited'),
        ('order', 'orders', 'ordered'),
        ('pay', 'pays', 'paid'),
        ('persuade', 'persuades', 'persuaded'),
        ('prefer', 'prefers', 'preferred'),
        ('remind', 'reminds', 'reminded'),
        ('teach', 'teaches', 'taught'),
        ('tell', 'tells', 'told'),
        ('train', 'trains', 'trained'),
        ('trust', 'trusts', 'trusted'),
        ('want', 'wants', 'wanted'),
        ('warn', 'warns', 'warned')
    ]


def __v_obj_ing():
    return [
        ('catch', 'catches', 'caught'),
        ('find', 'finds', 'found'),
        ('hear', 'hears', 'heard'),
        ('imagine', 'imagines', 'imagined'),
        ('notice', 'notices', 'noticed'),
        ('picture', 'pictures', 'pictured'),
        ('prevent', 'prevents', 'prevented'),
        ('see', 'sees', 'saw'),
        ('spot', 'spots', 'spotted'),
        ('stop', 'stops', 'stopped'),
        ('watch', 'watches', 'watched')
    ]
